export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_CATAGORIES = "SET_CATAGORIES";
export const SET_PRODUCTS_BY_ID = "SET_PRODUCTS_BY_ID";
export const SELL_PRODUCT = "SELL_PRODUCT";

//ERRORS
export const GET_ERRORS_PRODUCT = "GET_ERRORS_PRODUCT";
export const GET_ERRORS_CATAGORIES = "GET_ERRORS_CATAGORIES";
export const GET_ERRORS_LOGIN = "GET_ERRORS_LOGIN";
export const GET_ERRORS_REGISTER = "GET_ERRORS_REGISTER";
export const GET_ERRORS_PRODUCTBYID = "GET_ERRORS_PRODUCTBYID";
export const ERROR_SELLING_PRODUCT = "ERROR_SELLING_PRODUCT";

//logout
//export const RESET_CURRENT_USER = "RESET_CURRENT_USER";
